// Bones and teeth.
import type { KB, KBEntry } from '../types';

const B = (summary: string, type: string, articulations: string, features: string, extra: Partial<KBEntry> = {}): KBEntry => ({ summary, type, articulations, features, micro: 'osteon', ...extra });

export const BONES: KB = {
  // ---------------- skull ----------------
  'frontal bone': B('Shell-like bone forming the forehead, the roof of the orbits and the anterior cranial fossa.', 'Flat bone (skull vault), pneumatised by the frontal sinuses.', 'Parietal (coronal suture), nasal, maxillae, lacrimal, ethmoid, sphenoid and zygomatic bones.', 'Frontal squama, superciliary arches, glabella, supra-orbital notch/foramen, zygomatic process, orbital plates, frontal sinuses.', { ossification: 'Two membranous centres (8th week); the metopic suture usually fuses by age 2.', clinical: 'A persistent metopic suture can mimic a fracture on radiographs. Frontal sinusitis may spread to the orbit or anterior cranial fossa.' }),
  'parietal bone': B('Paired quadrilateral bone forming most of the roof and sides of the cranium.', 'Flat bone (skull vault).', 'The opposite parietal (sagittal suture), frontal (coronal), occipital (lambdoid), temporal (squamous) and sphenoid bones.', 'Parietal eminence and foramen, superior and inferior temporal lines; grooves for the middle meningeal vessels internally.', { ossification: 'Membranous, from two centres near the parietal eminence.', clinical: 'A fracture at the pterion (where frontal, parietal, temporal and sphenoid meet) can tear the middle meningeal artery, causing an extradural haematoma.' }),
  'occipital bone': B('Trapezoid bone forming the back and base of the cranium, pierced by the foramen magnum.', 'Flat/irregular bone of the skull base and vault.', 'Parietal (lambdoid suture), temporal and sphenoid bones; atlas via the occipital condyles (atlanto-occipital joints).', 'Foramen magnum, occipital condyles, hypoglossal canals, external occipital protuberance (inion), superior and inferior nuchal lines, basilar part (clivus), internal occipital protuberance.', { ossification: 'Part membranous (upper squama), part cartilaginous; basiocciput fuses with the sphenoid by ~25 years.' }),
  'temporal bone': B('Complex bone of the side and base of the skull housing the organs of hearing and balance.', 'Irregular bone with squamous, tympanic, petromastoid and styloid parts.', 'Parietal, occipital, sphenoid and zygomatic bones; mandible at the temporomandibular joint.', 'Zygomatic process, mandibular fossa and articular tubercle, external acoustic meatus, mastoid process and air cells, styloid process, petrous ridge, internal acoustic meatus, carotid canal, jugular foramen (with occipital).', { clinical: 'Fractures of the petrous part may cause bleeding or CSF leakage from the ear (otorrhoea) and facial nerve palsy. Mastoiditis can spread to the sigmoid sinus.' }),
  'sphenoid bone': B('Butterfly-shaped keystone bone at the centre of the skull base.', 'Irregular, pneumatised bone.', 'All other cranial bones and the palatine, zygomatic and vomer bones.', 'Body with sella turcica (pituitary fossa) and sphenoidal sinuses, greater and lesser wings, pterygoid processes; optic canal, superior orbital fissure, foramina rotundum, ovale and spinosum.', { aka: ['sphenoid'], clinical: 'The pituitary gland is approached surgically through the sphenoidal sinus (trans-sphenoidal surgery).' }),
  'ethmoid bone': B('Light, air-filled bone between the orbits forming part of the nasal cavity and anterior cranial fossa.', 'Irregular, pneumatised bone.', 'Frontal, sphenoid, nasal, maxillae, lacrimal, palatine, inferior nasal conchae and vomer.', 'Cribriform plate (olfactory nerve filaments), crista galli, perpendicular plate (nasal septum), ethmoidal labyrinth with air cells, superior and middle nasal conchae, orbital plate (lamina papyracea).', { aka: ['ethmoid', 'anterior cells of ethmoid', 'middle cells of ethmoid', 'posterior cells of ethmoid', 'ethmoidal cells'], clinical: 'Fracture of the cribriform plate can cause anosmia and CSF rhinorrhoea. The thin lamina papyracea lets ethmoid sinusitis spread into the orbit.' }),
  'maxilla': B('Paired bone of the upper jaw, forming part of the orbit, nose and palate.', 'Irregular pneumatised bone containing the maxillary sinus.', 'Opposite maxilla, frontal, ethmoid, nasal, zygomatic, lacrimal, palatine, vomer and inferior nasal concha.', 'Body with maxillary sinus, frontal, zygomatic, alveolar and palatine processes; infra-orbital foramen; upper tooth sockets.', { clinical: 'Le Fort fractures (I–III) describe patterns of midface fractures through the maxillae. Roots of upper molars may project into the maxillary sinus, so dental infection can cause sinusitis.' }),
  'mandible': B('The lower jaw — the largest, strongest and only freely movable bone of the skull.', 'Irregular bone (horseshoe-shaped body and two rami).', 'Temporal bones at the temporomandibular joints; lower teeth in its alveoli.', 'Body, ramus, angle, condylar process (head and neck), coronoid process, mandibular notch, mental foramen, mandibular foramen and lingula, mylohyoid line, mental protuberance.', { clinical: 'Often fractures in two places (e.g. body and opposite angle). Dislocation of the TMJ occurs anteriorly when the condyle passes in front of the articular tubercle (yawning).' }),
  'zygomatic bone': B('The cheekbone, forming the prominence of the cheek and part of the orbit.', 'Irregular bone.', 'Frontal, sphenoid, temporal (zygomatic arch) and maxilla.', 'Frontal, temporal and maxillary processes; zygomaticofacial and zygomaticotemporal foramina.', { clinical: 'Tripod (zygomaticomaxillary complex) fractures follow blows to the cheek and can entrap orbital contents.' }),
  'nasal bone': B('Small paired oblong bone forming the bridge of the nose.', 'Flat bone.', 'Frontal, ethmoid, the opposite nasal bone and the maxilla.', 'Upper margin thick and narrow; lower margin attached to the lateral nasal cartilage.', { clinical: 'The most frequently fractured facial bone.' }),
  'lacrimal bone': B('The smallest and most fragile facial bone, in the medial wall of the orbit.', 'Flat bone.', 'Frontal, ethmoid, maxilla and inferior nasal concha.', 'Posterior lacrimal crest and lacrimal groove forming the fossa for the lacrimal sac.'),
  'palatine bone': B('L-shaped bone forming the back of the hard palate and part of the nasal cavity and orbit.', 'Irregular bone.', 'Maxilla, sphenoid, ethmoid, inferior nasal concha, vomer and the opposite palatine bone.', 'Horizontal plate (posterior hard palate), perpendicular plate, pyramidal, orbital and sphenoidal processes; greater and lesser palatine foramina.'),
  'vomer': B('Thin plough-shaped bone forming the lower back part of the nasal septum.', 'Flat bone.', 'Sphenoid, ethmoid, maxillae and palatine bones; septal cartilage.', 'Alae on its upper border; posterior free border between the choanae.'),
  'inferior nasal concha': B('Scroll-like bone on the lateral wall of the nasal cavity.', 'Separate facial bone (the superior and middle conchae belong to the ethmoid).', 'Maxilla, lacrimal, ethmoid and palatine bones.', 'Lacrimal, maxillary and ethmoidal processes; the nasolacrimal duct opens below it into the inferior meatus.', { aka: ['inferior nasal concha bone'] }),
  'hyoid bone': B('U-shaped bone in the neck that does not articulate with any other bone.', 'Irregular bone suspended by muscles and ligaments.', 'None (attached by the stylohyoid ligaments and thyrohyoid membrane).', 'Body, greater and lesser horns; attachment for suprahyoid and infrahyoid muscles and the tongue.', { aka: ['hyoid'], clinical: 'Fracture of the hyoid is strongly suggestive of manual strangulation.' }),
  'sinus of frontal bone': B('Paired air-filled cavity in the frontal bone above the orbits.', 'Paranasal sinus.', 'Drains through the frontonasal duct into the middle meatus (semilunar hiatus).', 'Usually asymmetric, separated by a septum; absent in a small percentage of people.', { aka: ['frontal sinus'], micro: undefined }),
  'sinus of sphenoid bone': B('Paired air cavity within the body of the sphenoid, beneath the pituitary gland.', 'Paranasal sinus.', 'Drains into the spheno-ethmoidal recess above the superior concha.', 'Separated by an often-deviated septum; related to the optic nerves, internal carotid arteries and cavernous sinuses.', { aka: ['sphenoidal sinus'], micro: undefined }),

  // ---------------- vertebral column ----------------
  'cervical vertebra': B('Small vertebra of the neck (C1–C7) with a foramen in each transverse process for the vertebral artery.', 'Irregular bone.', 'Adjacent vertebrae by intervertebral discs (bodies) and zygapophysial (facet) joints; uncovertebral joints of Luschka between bodies C3–C7.', 'Small wide body, large triangular vertebral foramen, foramina transversaria, bifid spinous processes (C3–C6), anterior and posterior tubercles.', { aka: ['cervical vertebrae', 'typical cervical vertebra'], clinical: 'Osteophytes of the uncovertebral joints can narrow the intervertebral foramina and compress nerve roots (cervical radiculopathy).' }),
  'atlas': B('The first cervical vertebra (C1): a ring without a body that carries the skull.', 'Irregular bone.', 'Occipital condyles (atlanto-occipital joints: nodding) and axis (atlanto-axial joints: rotation).', 'Anterior and posterior arches, lateral masses with superior and inferior facets, facet for the dens, groove for the vertebral artery, no spinous process.', { aka: ['atlas c1', 'first cervical vertebra', 'c1'], clinical: 'Axial loading can burst the ring (Jefferson fracture). About half of head flexion–extension ("yes") occurs at the atlanto-occipital joints.' }),
  'axis': B('The second cervical vertebra (C2) with the tooth-like dens around which the atlas rotates.', 'Irregular bone.', 'Atlas (median and lateral atlanto-axial joints) and C3.', 'Dens (odontoid process) held by the transverse ligament of the atlas; strong bifid spinous process.', { aka: ['axis c2', 'second cervical vertebra', 'c2'], clinical: 'Fractures of the dens are common in falls in the elderly; the "hangman\'s fracture" is a bilateral fracture of the pars interarticularis of C2.' }),
  'vertebra prominens': B('The seventh cervical vertebra (C7), whose long spinous process is the first easily palpable one.', 'Irregular bone.', 'C6, T1.', 'Long non-bifid spinous process; small or absent foramina transversaria (vertebral artery usually enters at C6).', { aka: ['seventh cervical vertebra', 'c7'] }),
  'thoracic vertebra': B('One of twelve vertebrae (T1–T12) that articulate with the ribs.', 'Irregular bone.', 'Adjacent vertebrae; heads of ribs (costal facets on bodies) and tubercles of ribs (costal facets on transverse processes).', 'Heart-shaped body with costal facets, small round vertebral foramen, long downward-sloping spinous processes, facets oriented in the coronal plane (allowing rotation).', { aka: ['thoracic vertebrae'], clinical: 'Osteoporotic wedge fractures of thoracic bodies produce kyphosis ("dowager\'s hump").' }),
  'lumbar vertebra': B('One of five large vertebrae (L1–L5) of the lower back that bear most body weight.', 'Irregular bone.', 'Adjacent vertebrae through intervertebral discs and sagittally oriented facet joints; L5 with the sacrum.', 'Massive kidney-shaped body, thick short laminae, hatchet-shaped spinous processes, mammillary and accessory processes.', { aka: ['lumbar vertebrae'], clinical: 'Lumbar puncture is performed between L3/L4 or L4/L5, below the end of the spinal cord (L1/L2). Spondylolysis (pars defect) of L5 may lead to spondylolisthesis.' }),
  'sacrum': B('Wedge-shaped bone formed by the fusion of five sacral vertebrae, forming the back of the pelvis.', 'Irregular (fused) bone.', 'L5 (lumbosacral joint), hip bones (sacro-iliac joints) and coccyx.', 'Promontory, alae, anterior and posterior sacral foramina, median sacral crest, sacral hiatus, auricular surfaces.', { aka: ['fused sacrum'], clinical: 'The sacral hiatus is the entry point for caudal epidural anaesthesia.' }),
  'coccyx': B('The "tailbone": three to five fused rudimentary vertebrae.', 'Irregular (fused) bone.', 'Sacrum (sacrococcygeal symphysis).', 'Coccygeal cornua; attachment for gluteus maximus, coccygeus, levator ani and the anococcygeal body.', { clinical: 'Painful coccyx (coccydynia) often follows a fall onto the buttocks or childbirth.' }),

  // ---------------- thorax ----------------
  'rib': B('Curved flat bone forming the thoracic cage; typical ribs (3–9) have a head, neck, tubercle and shaft.', 'Flat bone.', 'Head: bodies of two adjacent vertebrae (costovertebral joint). Tubercle: transverse process (costotransverse joint). Anterior end: costal cartilage.', 'Head with two facets and crest, neck, tubercle, angle, shaft with costal groove for the intercostal vessels and nerve.', { aka: ['ribs', 'typical rib'], clinical: 'Rib fractures are most common just in front of the angle. Multiple fractures in two places produce a flail segment with paradoxical breathing.' }),
  'first rib': B('The shortest, broadest and most curved rib; landmark at the root of the neck.', 'Flat bone (atypical rib).', 'Head articulates with T1 only; costal cartilage joins the manubrium.', 'Scalene tubercle (scalenus anterior) with a groove for the subclavian vein in front and for the subclavian artery and lower trunk of the brachial plexus behind.', { clinical: 'A cervical rib or tight scalenes over the first rib can compress the neurovascular bundle (thoracic outlet syndrome).' }),
  'second rib': B('Thin, less curved rib roughly twice the length of the first.', 'Flat bone (atypical rib).', 'T1 and T2; costal cartilage at the sternal angle.', 'Tuberosity for serratus anterior. Its cartilage marks the sternal angle — the starting point for counting ribs.'),
  'false ribs': B('Ribs 8–10, whose cartilages join the cartilage above rather than the sternum.', 'Flat bones.', 'Vertebrae posteriorly; costal cartilage of the rib above anteriorly (forming the costal margin).', 'Typical rib features.'),
  'floating ribs': B('Ribs 11 and 12, which end freely in the posterior abdominal wall.', 'Flat bones (atypical).', 'Single vertebral body; no tubercle joint.', 'Short, no neck or tubercle; tips capped with cartilage.', { clinical: 'The 12th rib is a landmark for the kidney and pleura in posterior surgical approaches.' }),
  'costal cartilage': B('Bar of hyaline cartilage prolonging a rib anteriorly, contributing to chest wall elasticity.', 'Hyaline cartilage.', 'Ribs 1–7 to the sternum; 8–10 to the cartilage above.', 'Calcifies with age, reducing chest compliance.', { micro: 'cell' }),
  'sternum': B('Flat bone of the anterior chest: manubrium, body and xiphoid process.', 'Flat bone containing red marrow throughout life.', 'Clavicles and costal cartilages 1–7.', 'Jugular notch, sternal angle (manubriosternal joint at T4/5 level), xiphisternal joint.', { clinical: 'A common site for bone-marrow aspiration; split vertically (median sternotomy) for heart surgery.' }),
  'manubrium': B('Upper, broad part of the sternum.', 'Flat bone.', 'Clavicles (sternoclavicular joints), first costal cartilages and body of the sternum (manubriosternal joint, with the second costal cartilages).', 'Jugular (suprasternal) notch, clavicular notches, sternal angle.', { aka: ['manubrium of sternum'] }),
  'body of sternum': B('Long middle part of the sternum formed by four fused sternebrae.', 'Flat bone.', 'Manubrium, xiphoid process and costal cartilages 2–7.', 'Transverse ridges marking fused sternebrae; costal notches.', { aka: ['sternal body'] }),
  'xiphoid process': B('Small, variable lowest part of the sternum; cartilaginous in youth, ossified in adults.', 'Flat bone/cartilage.', 'Body of the sternum (xiphisternal joint at T9 level).', 'Attachment of the linea alba and diaphragm.', { clinical: 'Landmark for cardiopulmonary resuscitation hand position (above it) and pericardiocentesis (below it).' }),

  // ---------------- pectoral girdle & upper limb ----------------
  'clavicle': B('S-shaped long bone (collar bone) acting as a strut between the sternum and scapula.', 'Long bone that ossifies mostly in membrane — the first bone to ossify.', 'Manubrium (sternoclavicular joint), acromion (acromioclavicular joint); first rib via costoclavicular ligament.', 'Sternal and acromial ends, conoid tubercle and trapezoid line (coracoclavicular ligament), subclavian groove.', { clinical: 'The most frequently fractured bone, usually at the junction of middle and lateral thirds; the lateral fragment is pulled down by the weight of the arm.' }),
  'scapula': B('Triangular flat bone (shoulder blade) on the posterolateral chest wall, linking arm and trunk.', 'Flat bone.', 'Humerus (glenohumeral joint), clavicle (acromioclavicular joint); moves on the thoracic wall (scapulothoracic "joint").', 'Spine, acromion, coracoid process, glenoid cavity, supra- and infraspinous fossae, subscapular fossa, suprascapular notch, superior and inferior angles.', { clinical: 'Winging of the scapula indicates serratus anterior paralysis (long thoracic nerve injury).' }),
  'humerus': B('Long bone of the arm between shoulder and elbow.', 'Long bone.', 'Scapula (glenohumeral joint); radius and ulna (elbow joint).', 'Head, anatomical and surgical necks, greater and lesser tubercles, intertubercular sulcus, deltoid tuberosity, radial groove, medial and lateral epicondyles, trochlea, capitulum, olecranon and coronoid fossae.', { clinical: 'Fractures threaten nerves in contact with bone: surgical neck — axillary nerve; midshaft — radial nerve; medial epicondyle — ulnar nerve; supracondylar — median nerve and brachial artery.' }),
  'radius': B('Lateral bone of the forearm, rotating around the ulna in pronation and supination.', 'Long bone.', 'Humerus (capitulum), ulna (proximal and distal radio-ulnar joints), scaphoid and lunate (wrist joint).', 'Head, neck, radial tuberosity, interosseous border, dorsal (Lister) tubercle, styloid process, ulnar notch.', { clinical: 'Distal radius fracture from a fall on the outstretched hand (Colles fracture) produces a "dinner-fork" deformity. Radial head subluxation ("pulled elbow") is common in toddlers.' }),
  'ulna': B('Medial, stabilising bone of the forearm.', 'Long bone.', 'Humerus (trochlea — hinge of the elbow), radius (radio-ulnar joints); separated from the carpus by an articular disc.', 'Olecranon, coronoid process, trochlear notch, radial notch, ulnar tuberosity, head, styloid process.', { clinical: 'A fracture of the ulnar shaft with dislocation of the radial head is a Monteggia injury.' }),
  'scaphoid': B('Boat-shaped carpal bone in the proximal row, bridging both rows.', 'Short bone (carpal).', 'Radius, lunate, capitate, trapezium and trapezoid.', 'Tubercle palpable at the base of the thenar eminence; floor of the anatomical snuffbox.', { aka: ['scaphoid bone'], clinical: 'The most commonly fractured carpal bone; because blood enters distally, waist fractures may cause avascular necrosis of the proximal pole.' }),
  'lunate': B('Crescent-shaped carpal bone in the middle of the proximal row.', 'Short bone (carpal).', 'Radius, scaphoid, triquetrum, capitate and hamate.', 'Broad anterior surface; lies in the floor of the carpal tunnel.', { aka: ['lunate bone'], clinical: 'The most commonly dislocated carpal bone (anteriorly, compressing the median nerve). Avascular necrosis is Kienböck disease.' }),
  'triquetrum': B('Pyramidal carpal bone in the proximal row.', 'Short bone (carpal).', 'Lunate, pisiform and hamate; articular disc of the distal radio-ulnar joint.', 'Oval facet for the pisiform on its palmar surface.', { aka: ['triquetral', 'triquetrum bone', 'triquetral bone'] }),
  'pisiform': B('Pea-shaped sesamoid bone in the tendon of flexor carpi ulnaris.', 'Sesamoid (carpal) bone.', 'Triquetrum.', 'Palpable at the base of the hypothenar eminence; attachment of the flexor retinaculum and pisohamate ligament.', { aka: ['pisiform bone'] }),
  'trapezium': B('Carpal bone at the base of the thumb in the distal row.', 'Short bone (carpal).', 'Scaphoid, trapezoid, first and second metacarpals.', 'Saddle-shaped facet for the first metacarpal (thumb carpometacarpal joint); tubercle and groove for flexor carpi radialis.', { aka: ['trapezium bone'], clinical: 'Osteoarthritis of the saddle joint between trapezium and first metacarpal is very common in older people.' }),
  'trapezoid': B('Small wedge-shaped carpal bone in the distal row.', 'Short bone (carpal).', 'Scaphoid, trapezium, capitate and second metacarpal.', 'Wedge shape, broad dorsally.', { aka: ['trapezoid bone'] }),
  'capitate': B('Largest carpal bone, at the centre of the wrist.', 'Short bone (carpal).', 'Scaphoid, lunate, trapezoid, hamate and metacarpals 2–4.', 'Rounded head fitting into the concavity of scaphoid and lunate; the first carpal to ossify.', { aka: ['capitate bone'] }),
  'hamate': B('Wedge-shaped carpal bone with a hook projecting into the palm.', 'Short bone (carpal).', 'Lunate, triquetrum, capitate and metacarpals 4–5.', 'Hook of the hamate: attachment of the flexor retinaculum; lateral boundary of the ulnar canal (Guyon).', { aka: ['hamate bone'], clinical: 'The hook can fracture in golfers and batters, irritating the ulnar nerve.' }),
  'metacarpal bones': B('Five miniature long bones forming the skeleton of the palm.', 'Long bones.', 'Carpal bones (carpometacarpal joints) and proximal phalanges (metacarpophalangeal joints).', 'Base, shaft and head (knuckle).', { aka: ['metacarpals', 'metacarpal bone'], clinical: 'A "boxer\'s fracture" is a fracture of the fifth metacarpal neck from punching.' }),
  'first metacarpal': B('The short, thick metacarpal of the thumb.', 'Long bone.', 'Trapezium (saddle joint) and proximal phalanx of the thumb.', 'Rotated ~90° so the thumb faces the palm, allowing opposition.', { clinical: 'An intra-articular fracture of its base is a Bennett fracture.' }),
  'phalanges of hand': B('The 14 bones of the fingers: two in the thumb, three in each finger.', 'Long bones (miniature).', 'Metacarpal heads (MCP joints) and adjacent phalanges (interphalangeal joints).', 'Proximal, middle and distal phalanges; distal phalanges end in a tuberosity supporting the nail bed.', { aka: ['phalanx of hand', 'finger bones'], clinical: '"Mallet finger" is avulsion of the extensor tendon from the distal phalanx.' }),

  // ---------------- pelvic girdle & lower limb ----------------
  'hip bone': B('Large irregular bone formed by the fusion of ilium, ischium and pubis at the acetabulum.', 'Irregular (flat) bone.', 'Sacrum (sacro-iliac joint), the opposite hip bone (pubic symphysis) and femur (hip joint).', 'Iliac crest, anterior and posterior superior/inferior iliac spines, iliac fossa, auricular surface, greater and lesser sciatic notches, ischial spine and tuberosity, pubic crest and tubercle, obturator foramen, acetabulum.', { aka: ['os coxae', 'innominate bone', 'coxal bone', 'pelvic bone'], clinical: 'The iliac crest is a source of bone graft and marrow. Female pelves have a wider subpubic angle (>80°) and a rounder inlet than male pelves.' }),
  'femur': B('The longest and strongest bone of the body, in the thigh.', 'Long bone.', 'Hip bone (hip joint), tibia and patella (knee joint).', 'Head with fovea, neck (angle ~125°), greater and lesser trochanters, intertrochanteric line and crest, linea aspera, medial and lateral condyles and epicondyles, adductor tubercle, patellar surface, intercondylar fossa.', { clinical: 'Femoral neck fractures in the elderly may interrupt the retinacular arteries and cause avascular necrosis of the head. The shortened, laterally rotated leg is typical.' }),
  'patella': B('The kneecap — the largest sesamoid bone, in the quadriceps tendon.', 'Sesamoid bone.', 'Patellar surface of the femur.', 'Base (superior), apex (inferior), articular posterior surface with a larger lateral facet.', { clinical: 'Lateral dislocation is resisted by the lateral femoral condyle and vastus medialis. A bipartite patella is a normal variant.' }),
  'tibia': B('The shin bone — the large weight-bearing bone of the leg.', 'Long bone.', 'Femur (knee), fibula (superior and inferior tibiofibular joints), talus (ankle).', 'Medial and lateral condyles (tibial plateau), intercondylar eminence, tibial tuberosity, sharp anterior border, soleal line, medial malleolus.', { clinical: 'Its subcutaneous anterior surface makes open fractures common. The nutrient artery enters high, so distal-third fractures heal slowly.' }),
  'fibula': B('Slender lateral bone of the leg carrying little weight but forming the lateral malleolus.', 'Long bone.', 'Tibia (tibiofibular joints) and talus (ankle joint).', 'Head, neck (common fibular nerve winds around it), shaft, lateral malleolus.', { clinical: 'The common fibular nerve is vulnerable at the fibular neck (fractures, tight casts), causing foot drop. The fibula is used as a vascularised bone graft.' }),
  'talus': B('The ankle bone that transmits body weight from the tibia to the foot; no muscles attach to it.', 'Short bone (tarsal).', 'Tibia and fibula (ankle joint), calcaneus (subtalar joint) and navicular.', 'Head, neck, body with trochlea, lateral process, posterior process with groove for flexor hallucis longus.', { clinical: 'Neck fractures (forced dorsiflexion) risk avascular necrosis of the body because most blood enters distally.' }),
  'calcaneus': B('The heel bone — the largest tarsal bone.', 'Short bone (tarsal).', 'Talus (subtalar joint) and cuboid (calcaneocuboid joint).', 'Calcaneal tuberosity (Achilles tendon), sustentaculum tali, fibular trochlea, sulcus calcanei.', { clinical: 'Fractured by falls from a height onto the heels, often with vertebral compression fractures.' }),
  'navicular': B('Boat-shaped tarsal bone on the medial side of the foot.', 'Short bone (tarsal).', 'Talus, three cuneiforms and sometimes the cuboid.', 'Navicular tuberosity (tibialis posterior) palpable in front of the medial malleolus.', { aka: ['navicular bone', 'navicular bone of foot'] }),
  'cuboid': B('Cube-shaped tarsal bone on the lateral side of the foot.', 'Short bone (tarsal).', 'Calcaneus, lateral cuneiform, navicular (sometimes), and metatarsals 4–5.', 'Groove for the tendon of fibularis longus on its plantar surface.', { aka: ['cuboid bone'] }),
  'medial cuneiform': B('Largest of the three wedge-shaped cuneiform bones.', 'Short bone (tarsal).', 'Navicular, intermediate cuneiform and metatarsals 1–2.', 'Insertion of tibialis anterior and part of fibularis longus.', { aka: ['medial cuneiform bone'] }),
  'intermediate cuneiform': B('Smallest cuneiform bone.', 'Short bone (tarsal).', 'Navicular, medial and lateral cuneiforms, second metatarsal.', 'Recessed, creating a mortise that locks the second metatarsal base.', { aka: ['intermediate cuneiform bone'] }),
  'lateral cuneiform': B('Cuneiform bone between the intermediate cuneiform and cuboid.', 'Short bone (tarsal).', 'Navicular, intermediate cuneiform, cuboid and metatarsals 2–4.', 'Wedge shape contributing to the transverse arch.', { aka: ['lateral cuneiform bone'] }),
  'metatarsal bones': B('Five long bones of the forefoot.', 'Long bones.', 'Tarsal bones (tarsometatarsal joints) and proximal phalanges (MTP joints).', 'Base, shaft and head; heads bear weight in standing on tiptoe.', { aka: ['metatarsals', 'metatarsal bone'], clinical: 'Stress ("march") fractures commonly affect the second and third metatarsal shafts.' }),
  'first metatarsal': B('Short, thick metatarsal of the great toe, bearing much of the body weight.', 'Long bone.', 'Medial cuneiform and proximal phalanx of the great toe; two sesamoids under its head.', 'Tuberosity for fibularis longus.', { clinical: 'Lateral deviation of the great toe on it produces hallux valgus (bunion).' }),
  'fifth metatarsal': B('Lateral metatarsal with a prominent tuberosity at its base.', 'Long bone.', 'Cuboid and proximal phalanx of the little toe.', 'Tuberosity at the base for fibularis brevis.', { clinical: 'Avulsion of the tuberosity and the Jones fracture (of the proximal shaft) follow inversion injuries.' }),
  'phalanges of foot': B('The 14 bones of the toes: two in the great toe, three in each of the others.', 'Long bones (miniature).', 'Metatarsal heads and adjacent phalanges.', 'Proximal, middle and distal phalanges; the middle and distal phalanges of the little toe are often fused.', { aka: ['phalanx of foot', 'toe bones'] }),
  'sesamoid bones': B('Small bones embedded in tendons, protecting them and improving leverage (e.g. patella, sesamoids under the first metatarsal head).', 'Sesamoid bones.', 'Glide on the adjacent bone surface.', 'Two constant sesamoids lie in the flexor hallucis brevis tendons under the first metatarsal head.', { aka: ['sesamoid bones of foot', 'sesamoid bone of foot'] }),

  'compact bone': B('Dense outer shell of bones, made of tightly packed osteons (Haversian systems).', 'Bone tissue (cortical bone), ~80% of skeletal mass.', 'Forms the cortex of all bones and the shafts of long bones.', 'Osteons ~200 µm across with a central canal, concentric lamellae and osteocytes in lacunae linked by canaliculi; Volkmann canals connect osteons.', { aka: ['compact bone tissue', 'cortical bone'] }),
  'spongy bone': B('Lattice of bony trabeculae aligned along lines of stress, with marrow in the spaces.', 'Bone tissue (cancellous/trabecular bone).', 'Fills the ends of long bones, vertebral bodies, flat bones.', 'Trabeculae lined by endosteum; red marrow between them produces blood cells.', { aka: ['trabecular bone tissue', 'trabecular bone', 'cancellous bone'], clinical: 'Loses mass fastest in osteoporosis, so vertebral bodies and the femoral neck fracture easily.' }),

  // ---------------- teeth ----------------
  'teeth': B('Hard structures of the jaws for biting and chewing; adults normally have 32 permanent teeth.', 'Composed of enamel (hardest tissue of the body), dentine, cementum and pulp.', 'Held in the alveoli of the maxilla and mandible by the periodontal ligament (gomphosis).', 'Crown, neck and root(s); pulp cavity with nerves and vessels.', { aka: ['tooth'], micro: undefined }),
  'incisor teeth': B('Chisel-shaped front teeth (two per quadrant) for cutting.', 'Permanent teeth, single-rooted.', 'Alveoli of the premaxillary part of maxilla / mandible.', 'Sharp incisal edge; medial (central) and lateral incisors.', { aka: ['incisors', 'medial incisor', 'lateral incisor', 'upper medial incisor', 'upper lateral incisor', 'lower medial incisor', 'lower lateral incisor'], micro: undefined }),
  'canine teeth': B('Single long-rooted pointed teeth at the corners of the mouth for tearing.', 'Permanent teeth, longest roots.', 'Alveoli of maxilla / mandible.', 'Conical cusp; the upper canine root produces the canine eminence.', { aka: ['canines', 'canine tooth', 'upper canine', 'lower canine'], micro: undefined }),
  'premolar teeth': B('Two teeth per quadrant with two cusps for crushing.', 'Permanent teeth (no deciduous predecessors of the same type).', 'Alveoli of maxilla / mandible.', 'Bicuspid crowns; upper first premolar usually has two roots.', { aka: ['premolars', 'bicuspids'], micro: undefined }),
  'molar teeth': B('Large grinding teeth at the back of the mouth, three per quadrant including the wisdom tooth.', 'Permanent teeth, multi-rooted.', 'Alveoli of maxilla / mandible.', 'Broad crowns with 4–5 cusps; upper molars 3 roots, lower molars 2 roots.', { aka: ['molars'], clinical: 'Impacted third molars (wisdom teeth) are common; roots of lower molars lie close to the inferior alveolar nerve.', micro: undefined }),
};
