// Brain: cerebral cortex, basal nuclei, diencephalon, brainstem, cerebellum, ventricles.
import type { KB, KBEntry } from '../types';

const Br = (summary: string, location: string, func: string, extra: Partial<KBEntry> = {}): KBEntry => ({ summary, location, function: func, micro: 'neuron', ...extra });

export const BRAIN: KB = {
  'brain': Br('The brain (~1.4 kg) contains ~86 billion neurons: cerebrum, diencephalon, brainstem and cerebellum, bathed in cerebrospinal fluid.', 'Cranial cavity.', 'Perception, movement, cognition, emotion, memory, homeostasis and control of every body system.', { blood: 'Internal carotid and vertebral arteries joined in the circle of Willis; ~15% of cardiac output.' }),
  'cerebral hemisphere': Br('Each half of the cerebrum: a folded grey-matter cortex over white matter and deep nuclei, divided into frontal, parietal, temporal, occipital and insular lobes.', 'Supratentorial compartment.', 'Higher functions; each hemisphere controls and senses the opposite side of the body.', { aka: ['white matter of cerebral hemisphere', 'white matter of forebrain', 'white matter of telencephalon', 'cerebrum'], clinical: 'The left hemisphere is dominant for language in ~95% of right-handed people.' }),

  // ---------------- frontal lobe ----------------
  'precentral gyrus': Br('Gyrus in front of the central sulcus containing the primary motor cortex (Brodmann area 4).', 'Frontal lobe.', 'Initiates voluntary movement of the opposite side; body represented upside down as a motor homunculus (face lateral, leg medial).', { clinical: 'Lesions cause contralateral weakness; an irritative focus causes a Jacksonian march seizure.' }),
  'superior frontal gyrus': Br('Uppermost frontal gyrus, running parallel to the midline.', 'Frontal lobe.', 'Includes the supplementary motor area (planning of movement) and contributes to working memory and self-awareness.'),
  'middle frontal gyrus': Br('Middle horizontal gyrus of the frontal lobe.', 'Frontal lobe.', 'Dorsolateral prefrontal cortex: executive function, working memory; frontal eye field (voluntary saccades) at its back end.'),
  'inferior frontal gyrus': Br('Lowest frontal gyrus, with opercular, triangular and orbital parts.', 'Frontal lobe.', 'In the dominant hemisphere its opercular and triangular parts form Broca\'s area (speech production).', { aka: ['opercular part of inferior frontal gyrus', 'triangular part of inferior frontal gyrus', 'orbital part of inferior frontal gyrus', 'frontal operculum'], clinical: 'Damage causes expressive (Broca) aphasia — slow, effortful speech with preserved comprehension.' }),
  'orbital gyri': Br('Gyri on the orbital surface of the frontal lobe.', 'Frontal lobe, above the orbits.', 'Orbitofrontal cortex: decision-making, reward, social behaviour and smell (secondary olfactory cortex).', { aka: ['orbital gyrus', 'medial orbital gyrus', 'lateral orbital gyrus', 'intermediate orbital gyrus', 'anterior orbital gyrus', 'posterior orbital gyrus', 'frontomarginal gyrus', 'lateral olfactory gyrus'], clinical: 'Orbitofrontal injury (e.g. Phineas Gage) alters personality and judgement.' }),
  'gyrus rectus': Br('Straight gyrus along the medial margin of the orbital surface.', 'Frontal lobe, beside the olfactory tract.', 'Part of the orbitofrontal/limbic network.', { aka: ['straight gyrus'] }),
  'frontal pole': Br('The anterior tip of the frontal lobe.', 'Front of the cranial cavity.', 'Rostral prefrontal cortex: complex planning, multitasking and abstract reasoning.', { aka: ['rostral gyrus', 'paracingulate gyrus'] }),
  'paracentral lobule': Br('Medial continuation of the precentral and postcentral gyri.', 'Medial surface of the hemisphere.', 'Motor and sensory representation of the opposite leg and foot; cortical control of micturition.', { aka: ['anterior segment of paracentral lobule', 'paracentral lobule caudal part', 'paracentral lobule rostral part'], clinical: 'A parasagittal meningioma here causes leg weakness and urinary incontinence.' }),

  // ---------------- parietal lobe ----------------
  'postcentral gyrus': Br('Gyrus behind the central sulcus containing the primary somatosensory cortex (areas 3, 1, 2).', 'Parietal lobe.', 'Receives touch, pain, temperature and position sense from the opposite side (sensory homunculus).'),
  'superior parietal lobule': Br('Upper part of the parietal lobe behind the postcentral gyrus.', 'Parietal lobe.', 'Spatial orientation, integration of vision with body position, reaching.', { aka: ['supraparietal lobule'], clinical: 'Lesions cause sensory neglect and difficulty recognising objects by touch (astereognosis).' }),
  'supramarginal gyrus': Br('Gyrus arching around the end of the lateral sulcus.', 'Inferior parietal lobule.', 'Phonological processing, empathy and tool use; part of Wernicke\'s territory.'),
  'angular gyrus': Br('Gyrus arching around the end of the superior temporal sulcus.', 'Inferior parietal lobule.', 'Reading, writing, calculation and semantic processing.', { clinical: 'Dominant-side lesions cause Gerstmann syndrome: agraphia, acalculia, finger agnosia and left–right confusion.' }),
  'precuneus': Br('Medial parietal region in front of the cuneus.', 'Medial surface of the parietal lobe.', 'Visuospatial imagery, episodic memory retrieval and self-awareness (default mode network hub).', { aka: ['precuneus cortex'] }),
  'parietal operculum': Br('Part of the parietal lobe covering the insula above the lateral sulcus.', 'Parietal lobe.', 'Secondary somatosensory cortex.'),

  // ---------------- temporal lobe ----------------
  'superior temporal gyrus': Br('Uppermost temporal gyrus below the lateral sulcus.', 'Temporal lobe.', 'Auditory processing; its posterior part in the dominant hemisphere is Wernicke\'s area (language comprehension).', { aka: ['anterior part of superior temporal gyrus', 'posterior part of superior temporal gyrus', 'superior temporal gyrus lateral part'], clinical: 'Damage causes receptive (Wernicke) aphasia — fluent but meaningless speech with poor comprehension.' }),
  'transverse temporal gyrus': Br('Heschl\'s gyri on the upper surface of the superior temporal gyrus.', 'Temporal lobe, in the floor of the lateral sulcus.', 'Primary auditory cortex (areas 41, 42), tonotopically organised.', { aka: ['transverse temporal gyri', 'transverse temporal gyrus heschls gyrus', 'heschl gyrus'] }),
  'planum temporale': Br('Triangular area behind Heschl\'s gyrus.', 'Upper surface of the temporal lobe.', 'Auditory association and language; usually larger on the left.', { aka: ['temporal plane'] }),
  'planum polare': Br('Upper temporal surface in front of Heschl\'s gyrus.', 'Temporal lobe.', 'Processing of complex sounds such as music.'),
  'middle temporal gyrus': Br('Middle gyrus of the temporal lobe.', 'Temporal lobe.', 'Semantic memory, language and visual motion (area MT near its back).'),
  'inferior temporal gyrus': Br('Lowest gyrus on the lateral surface of the temporal lobe.', 'Temporal lobe.', 'Visual object recognition (ventral "what" stream).'),
  'temporal pole': Br('Anterior tip of the temporal lobe.', 'Middle cranial fossa.', 'Semantic memory and social-emotional processing.', { clinical: 'Atrophy here characterises semantic dementia.' }),
  'fusiform gyrus': Br('Gyrus on the inferior surface between the inferior temporal and parahippocampal gyri.', 'Temporal and occipital lobes.', 'Face (fusiform face area) and word-form recognition.', { aka: ['occipitotemporal fusiform gyrus temporal part', 'occipital fusiform gyrus', 'lateral occipitotemporal gyrus', 'lateral occipitotemporal fusiform gyrus occipital part'], clinical: 'Lesions cause prosopagnosia (inability to recognise faces).' }),
  'parahippocampal gyrus': Br('Medial temporal gyrus surrounding the hippocampus; its front hooks as the uncus.', 'Medial temporal lobe.', 'Memory encoding (entorhinal cortex is the gateway to the hippocampus) and scene recognition.', { aka: ['anterior parahippocampal gyrus', 'posterior parahippocampal gyrus', 'medial occipitotemporal gyrus', 'perirhinal gyrus', 'perirhinal gyrus rostral part of fugt', 'gyrus ambiens', 'isthmus of cingulate gyrus'], clinical: 'The entorhinal cortex is among the first areas affected in Alzheimer disease.' }),

  // ---------------- occipital lobe ----------------
  'occipital lobe': Br('Posterior lobe of the hemisphere, the visual brain.', 'Behind the parieto-occipital sulcus.', 'Primary visual cortex (area 17) around the calcarine sulcus and visual association areas.', { aka: ['occipital pole', 'superior occipital gyrus', 'superior occipital gyri', 'inferior occipital gyrus', 'lateral occipital gyrus', 'middle occipital gyrus'], clinical: 'Damage to one occipital lobe causes a contralateral homonymous hemianopia, often with macular sparing.' }),
  'cuneus': Br('Wedge-shaped medial occipital gyrus above the calcarine sulcus.', 'Medial occipital lobe.', 'Primary visual cortex for the opposite lower visual field.', { aka: ['cuneus cortex'] }),
  'lingual gyrus': Br('Tongue-shaped medial occipital gyrus below the calcarine sulcus.', 'Medial occipital lobe.', 'Primary and secondary visual cortex for the opposite upper visual field; colour and letter processing.'),

  // ---------------- limbic & insula ----------------
  'cingulate gyrus': Br('Arch-shaped gyrus above the corpus callosum.', 'Medial surface of the hemisphere.', 'Emotion, motivation, pain affect (anterior part) and memory/spatial processing (posterior part).', { aka: ['anterior cingulate gyrus', 'posterior cingulate gyrus', 'cingulate gyrus rostral anterior part', 'cingulate gyrus caudal posterior part'] }),
  'subcallosal area': Br('Small cortical area below the rostrum of the corpus callosum.', 'Medial frontal lobe.', 'Limbic function; target of deep brain stimulation for depression.', { aka: ['subcallosal gyrus', 'subcallosal gyrus parolfactory gyrus', 'septum of telencephalon'] }),
  'hippocampus': Br('Curved, seahorse-shaped cortical structure in the floor of the inferior horn of the lateral ventricle.', 'Medial temporal lobe.', 'Formation of new declarative memories and spatial navigation.', { aka: ['head of hippocampus', 'body of hippocampus', 'tail of hippocampus', 'amygdalohippocampal area'], clinical: 'Bilateral damage causes profound anterograde amnesia; hippocampal sclerosis is a common cause of temporal lobe epilepsy.' }),
  'amygdala': Br('Almond-shaped group of nuclei in front of the hippocampus.', 'Anterior medial temporal lobe.', 'Emotional learning, fear and threat detection; emotional coloring of memories.', { aka: ['amygdaloid complex', 'amygdaloid body', 'anterior amygdaloid area', 'basolateral nucleus basal nucleus', 'basomedial nucleus accessory basal nucleus', 'lateral nucleus', 'medial nucleus', 'anterior cortical nucleus', 'posterior cortical nucleus', 'central nuclear group'], clinical: 'Bilateral damage (Klüver–Bucy syndrome) produces loss of fear and hyperorality.' }),
  'fornix': Br('Arched bundle of fibres carrying output from the hippocampus to the mammillary bodies and septal area.', 'Beneath the corpus callosum, forming the roof edge of the lateral ventricles.', 'Part of the Papez memory circuit.', { aka: ['fornix of forebrain', 'fornix of brain', 'commissure of fornix of forebrain', 'hippocampal commissure'] }),
  'septal nuclei': Br('Grey matter in the septal area below the rostrum of the corpus callosum.', 'Medial basal forebrain.', 'Reward and pleasure circuits; cholinergic input to the hippocampus.', { aka: ['septal area', 'septum pellucidum'] }),
  'insula': Br('Hidden fifth lobe deep in the lateral sulcus, covered by the opercula.', 'Floor of the lateral sulcus.', 'Interoception (awareness of body states), taste, visceral sensation, emotion and speech planning.', { aka: ['long insular gyri', 'short insular gyri', 'limen insula', 'frontal agranular insular cortex area fl', 'temporal agranular insular cortex area tl', 'circular sulcus of insula'] }),
  'olfactory bulb': Br('Oval swelling on the cribriform plate where olfactory nerve fibres synapse.', 'Under the frontal lobe.', 'First relay of smell.', { aka: ['olfactory tract', 'anterior olfactory nucleus', 'piriform cortex', 'piriform region'] }),

  // ---------------- basal nuclei ----------------
  'caudate nucleus': Br('C-shaped nucleus following the lateral ventricle (head, body, tail).', 'Lateral wall of the lateral ventricle.', 'With the putamen (striatum) — planning of movement, habit and reward learning.', { aka: ['head of caudate', 'body of caudate', 'tail of caudate', 'striatum'], clinical: 'Atrophy of the caudate is characteristic of Huntington disease (chorea).' }),
  'putamen': Br('Large lateral nucleus of the lentiform complex.', 'Lateral to the globus pallidus and internal capsule.', 'Motor part of the striatum: learning and execution of movement sequences.', { aka: ['posteroventral putamen', 'lentiform nucleus'], clinical: 'The most common site of hypertensive intracerebral haemorrhage.' }),
  'globus pallidus': Br('Pale, medial part of the lentiform nucleus with external and internal segments.', 'Medial to the putamen.', 'Main output nucleus of the basal ganglia to the thalamus; inhibits unwanted movement.', { aka: ['external segment of globus pallidus', 'internal segment of globus pallidus', 'pallidum'], clinical: 'The internal segment is a deep brain stimulation target for Parkinson disease and dystonia.' }),
  'nucleus accumbens': Br('Ventral part of the striatum where caudate and putamen meet.', 'Ventral forebrain.', 'Reward, motivation and addiction (mesolimbic dopamine pathway).'),
  'claustrum': Br('Thin sheet of grey matter between the insula and the putamen.', 'Deep to the insula.', 'Highly connected with the cortex; proposed role in attention and consciousness.'),
  'basal forebrain': Br('Region below the striatum including the nucleus basalis of Meynert.', 'Ventral forebrain.', 'Cholinergic projections to the cortex supporting attention and memory.', { aka: ['nucleus basalis'], clinical: 'Loss of these cholinergic neurons contributes to Alzheimer disease.' }),
  'substantia nigra': Br('Pigmented nucleus in the midbrain (pars compacta and pars reticulata).', 'Midbrain, behind the cerebral peduncle.', 'Dopaminergic neurons modulate the striatum; the pars reticulata is a basal-ganglia output nucleus.', { clinical: 'Loss of its dopaminergic neurons causes Parkinson disease (tremor, rigidity, bradykinesia).' }),
  'subthalamic nucleus': Br('Lens-shaped nucleus below the thalamus.', 'Diencephalon/midbrain junction.', 'Excites the globus pallidus internus, braking movement.', { clinical: 'Lesions cause hemiballismus; it is the most common DBS target in Parkinson disease.' }),

  // ---------------- diencephalon ----------------
  'thalamus': Br('Egg-shaped paired mass of nuclei forming the walls of the third ventricle — the gateway to the cortex.', 'Diencephalon.', 'Relays and modulates sensory (except smell), motor, limbic and arousal signals to the cortex.', { aka: ['anterior nuclear complex of thalamus', 'mediodorsal nucleus of thalamus', 'lateral dorsal nucleus of thalamus', 'lateral posterior nucleus of thalamus', 'pulvinar of thalamus', 'ventral anterior nucleus of thalamus', 'ventral lateral nucleus of thalamus', 'ventral posterior lateral nucleus', 'ventral posterior medial nucleus', 'centromedian nucleus of thalamus', 'parafascicular nucleus of thalamus', 'reuniens nucleus medioventral nucleus of thalamus', 'midline nuclear complex', 'intralaminar nuclei'], clinical: 'Thalamic strokes cause contralateral sensory loss and sometimes severe central pain (Dejerine–Roussy syndrome).' }),
  'lateral geniculate body': Br('Thalamic relay nucleus of the visual pathway.', 'Posterior thalamus.', 'Relays retinal input from the optic tract to the primary visual cortex via the optic radiation.', { aka: ['dorsal lateral geniculate nucleus'] }),
  'medial geniculate body': Br('Thalamic relay nucleus of the auditory pathway.', 'Posterior thalamus, below the pulvinar.', 'Relays auditory input from the inferior colliculus to the auditory cortex.', { aka: ['medial geniculate nuclei'] }),
  'hypothalamus': Br('Small region (~4 g) below the thalamus forming the floor of the third ventricle.', 'Diencephalon, above the pituitary.', 'Master regulator of homeostasis: temperature, hunger, thirst, sleep, circadian rhythm, autonomic and endocrine control (via the pituitary).', { aka: ['tuberal region of hypothalamus', 'preoptic region of hypothalamus', 'supraoptic region of hypothalamus', 'mammillary region of hypothalamus', 'tuber cinereum', 'lamina terminalis'], clinical: 'Hypothalamic lesions may cause diabetes insipidus, obesity or temperature dysregulation.' }),
  'mammillary body': Br('Pair of small round nuclei on the underside of the hypothalamus.', 'Floor of the diencephalon.', 'Memory (Papez circuit); receives the fornix and projects via the mammillothalamic tract.', { aka: ['mamillary body', 'mammillothalamic tract'], clinical: 'Atrophy is characteristic of Wernicke–Korsakoff syndrome (thiamine deficiency).' }),
  'habenula': Br('Small epithalamic nucleus near the pineal gland.', 'Epithalamus, dorsal thalamus.', 'Links forebrain limbic areas with midbrain; involved in aversion and reward prediction.', { aka: ['habenular nuclei', 'stria medullaris of thalamus', 'stria medullaris thalami'] }),
  'zona incerta': Br('Thin strip of grey matter between the thalamus and subthalamic nucleus.', 'Subthalamus.', 'Integration of sensory and motor signals; attention.'),
  'pretectal region': Br('Region at the junction of midbrain and thalamus.', 'In front of the superior colliculus.', 'Pupillary light reflex (sends to both Edinger–Westphal nuclei).', { clinical: 'Pretectal lesions cause light–near dissociation of the pupils.' }),
  'stria terminalis': Br('Fibre bundle running in the groove between caudate and thalamus.', 'Floor of the lateral ventricle.', 'Main output of the amygdala to the hypothalamus and bed nucleus.', { aka: ['bed nucleus of stria terminalis'] }),

  // ---------------- commissures & white matter ----------------
  'corpus callosum': Br('Largest commissure (~200 million axons) connecting the two cerebral hemispheres.', 'Floor of the longitudinal fissure, roof of the lateral ventricles (rostrum, genu, body, splenium).', 'Transfers information between hemispheres.', { clinical: 'Split-brain surgery (callosotomy) for epilepsy shows each hemisphere\'s specialisation.' }),
  'anterior commissure': Br('Small bundle crossing in front of the fornix columns.', 'Lamina terminalis.', 'Connects the temporal lobes and olfactory areas of both sides.'),
  'posterior commissure': Br('Fibre bundle crossing above the cerebral aqueduct.', 'Junction of midbrain and diencephalon.', 'Carries fibres for the consensual pupillary light reflex and vertical gaze.'),
  'internal capsule': Br('Compact V-shaped band of white matter between the thalamus, caudate and lentiform nucleus.', 'Deep cerebral hemisphere.', 'Carries almost all fibres between the cortex and brainstem/spinal cord (corticospinal fibres in the posterior limb).', { clinical: 'A small lacunar stroke here causes a dense contralateral hemiplegia.' }),
  'white matter of hindbrain': Br('Fibre tracts of the pons, medulla and cerebellum.', 'Posterior cranial fossa.', 'Connects brainstem nuclei, cerebellum, cerebrum and spinal cord.'),

  // ---------------- brainstem ----------------
  'midbrain': Br('Shortest part of the brainstem, passing through the tentorial notch.', 'Between the diencephalon and the pons.', 'Contains nuclei of CN III and IV, the substantia nigra and red nucleus; relays auditory and visual reflexes (colliculi).', { aka: ['mesencephalon', 'midbrain tegmentum', 'tegmentum of midbrain'] }),
  'cerebral peduncle': Br('Massive fibre bundles on the front of the midbrain carrying descending motor fibres.', 'Ventral midbrain.', 'Carries corticospinal, corticobulbar and corticopontine fibres.', { aka: ['peduncle of midbrain', 'base of peduncle', 'crus cerebri', 'cerebral peduncle crus cerebri'], clinical: 'Weber syndrome: ipsilateral CN III palsy with contralateral hemiplegia.' }),
  'superior colliculus': Br('Upper pair of the four bumps on the back of the midbrain.', 'Dorsal midbrain (tectum).', 'Visual reflexes: orienting the eyes and head towards stimuli.', { aka: ['brachium of superior colliculus'] }),
  'inferior colliculus': Br('Lower pair of the midbrain tectum.', 'Dorsal midbrain.', 'Auditory relay to the medial geniculate body; sound localisation.', { aka: ['brachium of inferior colliculus'] }),
  'red nucleus': Br('Iron-rich reddish nucleus of the midbrain tegmentum.', 'Midbrain.', 'Motor coordination; origin of the rubrospinal tract.'),
  'interpeduncular fossa': Br('Depression between the cerebral peduncles.', 'Ventral midbrain.', 'Exit of the oculomotor nerves; contains posterior perforated substance.'),
  'pons': Br('Bulging "bridge" of the brainstem connecting the cerebrum with the cerebellum.', 'Between midbrain and medulla, in front of the cerebellum.', 'Relays cortex to cerebellum (pontine nuclei); contains nuclei of CN V–VIII; controls breathing rhythm and sleep.', { aka: ['pontine tegmentum', 'pontine nuclear group', 'basilar part of pons'], clinical: 'Central pontine myelinolysis follows over-rapid correction of hyponatraemia.' }),
  'medulla oblongata': Br('Lowest part of the brainstem, continuous with the spinal cord at the foramen magnum.', 'Posterior cranial fossa.', 'Vital centres for breathing, heart rate and blood pressure; nuclei of CN IX–XII; the pyramids cross (decussation) here.', { aka: ['medulla', 'tegmentum of medulla oblongata', 'pyramidal part of medulla oblongata', 'pyramid of medulla oblongata', 'inferior olive', 'olive'], clinical: 'Compression by tonsillar herniation through the foramen magnum is rapidly fatal.' }),
  'cranial nerve nuclei': Br('Brainstem nuclei where cranial nerve fibres begin (motor) or end (sensory).', 'Midbrain, pons and medulla.', 'Motor, parasympathetic and sensory control of the head and neck and, via the vagus, the viscera.', { aka: ['nucleus of oculomotor nerve', 'accessory nucleus of oculomotor nerve', 'nucleus of trochlear nerve', 'nucleus of abducens nerve', 'motor nucleus of facial nerve', 'nucleus of hypoglossal nerve', 'posterior nucleus of vagus nerve', 'nucleus ambiguus', 'superior salivatory nucleus', 'inferior salivatory nucleus', 'vestibular nuclei', 'anterior cochlear nucleus', 'posterior cochlear nucleus'] }),

  // ---------------- cerebellum ----------------
  'cerebellum': Br('"Little brain" behind the brainstem containing more than half of all brain neurons.', 'Posterior cranial fossa, under the tentorium.', 'Coordination, balance, timing and motor learning; also cognitive functions.', { aka: ['cerebellar hemisphere', 'lateral hemisphere of cerebellum', 'paravermis of cerebellum', 'anterior quadrangular lobule', 'posterior quadrangular lobule', 'superior semilunar lobule', 'inferior semilunar lobule', 'biventral lobule', 'gracile lobule', 'tonsil of cerebellum', 'flocculus', 'peduncle of flocculus', 'central lobule', 'wing of central lobule', 'lingula of cerebellum'], clinical: 'Hemisphere lesions cause ipsilateral ataxia, intention tremor and dysdiadochokinesia; the tonsils can herniate through the foramen magnum.' }),
  'cerebellar vermis': Br('Midline "worm" of the cerebellum.', 'Between the cerebellar hemispheres.', 'Posture and gait; eye movements (flocculonodular lobe).', { aka: ['vermis', 'culmen', 'declive', 'folium of vermis', 'tuber of vermis', 'pyramis of vermis', 'uvula of vermis', 'nodule of vermis'], clinical: 'Vermis degeneration from chronic alcohol use causes a broad-based ataxic gait.' }),
  'cerebellar deep nuclei': Br('Dentate, emboliform, globose and fastigial nuclei in the cerebellar white matter.', 'Cerebellar white matter.', 'The sole output of the cerebellum.', { aka: ['dentate nucleus', 'deep cerebellar nuclei'] }),
  'cerebellar peduncles': Br('Three paired fibre bundles connecting the cerebellum to the brainstem.', 'Superior (midbrain), middle (pons), inferior (medulla).', 'Superior: mainly output; middle: input from the cortex via pontine nuclei; inferior: input from the spinal cord and vestibular system.', { aka: ['superior cerebellar peduncle', 'middle cerebellar peduncle', 'inferior cerebellar peduncle', 'superior cerebellar peduncle brachium conjunctivum'] }),

  // ---------------- ventricles & CSF ----------------
  'lateral ventricle': Br('Largest CSF-filled cavity, one in each hemisphere, C-shaped with anterior, posterior and inferior horns.', 'Cerebral hemisphere.', 'Produces (choroid plexus) and contains cerebrospinal fluid.', { aka: ['anterior horn of lateral ventricle', 'posterior horn of lateral ventricle', 'inferior horn of lateral ventricle', 'body of lateral ventricle', 'atrium of lateral ventricle', 'lateral ventricles'], micro: undefined, clinical: 'Enlarged ventricles (hydrocephalus) result from obstructed CSF flow or impaired absorption.' }),
  'third ventricle': Br('Narrow midline slit between the two thalami.', 'Diencephalon.', 'Connects the lateral ventricles (via the interventricular foramina) with the cerebral aqueduct.', { aka: ['interventricular foramen'], micro: undefined }),
  'cerebral aqueduct': Br('Narrow channel through the midbrain.', 'Midbrain.', 'Carries CSF from the third to the fourth ventricle.', { aka: ['aqueduct of midbrain'], micro: undefined, clinical: 'Aqueductal stenosis is the commonest cause of congenital hydrocephalus.' }),
  'fourth ventricle': Br('Tent-shaped cavity between the pons/medulla and the cerebellum.', 'Hindbrain.', 'CSF leaves it through the median and lateral apertures into the subarachnoid space.', { micro: undefined }),
  'choroid plexus': Br('Tufts of capillaries covered by specialised ependyma in the ventricles.', 'Lateral, third and fourth ventricles.', 'Secretes ~500 mL of cerebrospinal fluid per day.', { aka: ['choroid plexus of cerebral hemisphere'], micro: 'capillary' }),
};
