// Eye, lacrimal apparatus, ear and skin.
import type { KB, KBEntry } from '../types';

const S = (summary: string, location: string, func: string, extra: Partial<KBEntry> = {}): KBEntry => ({ summary, location, function: func, ...extra });

export const SENSES: KB = {
  // =============================== eye ===============================
  'eyeball': S('Sphere ~24 mm across with three coats: fibrous (sclera, cornea), vascular (choroid, ciliary body, iris) and neural (retina).', 'Anterior orbit, cushioned by fat.', 'Focuses light onto the retina and converts it into nerve signals.', { aka: ['eye', 'globe', 'anterior segment of eyeball', 'posterior segment of eyeball', 'suspensory ligament of eyeball'], micro: 'neuron' }),
  'cornea': S('Transparent, avascular front window of the eye (~0.5 mm thick), continuous with the sclera at the limbus.', 'Anterior sixth of the fibrous coat.', 'Provides about two-thirds of the eye\'s refractive power (~43 dioptres).', { aka: ['corneoscleral junction', 'limbus'], innervation: 'Long ciliary nerves (V1) — extremely sensitive (corneal reflex).', histology: 'Five layers: epithelium, Bowman layer, stroma of precisely arranged collagen lamellae, Descemet membrane, endothelium that pumps water out.', clinical: 'Refractive surgery (LASIK) reshapes the corneal stroma. Corneal transplants rarely reject because the cornea is avascular.' }),
  'sclera': S('Tough white outer coat covering the posterior five-sixths of the eyeball.', 'Eyeball.', 'Maintains the shape of the eye and gives attachment to the extraocular muscles.', { clinical: 'A yellow sclera (really the conjunctiva over it) is an early sign of jaundice.' }),
  'choroid': S('Dark, highly vascular layer between sclera and retina.', 'Posterior eyeball.', 'Nourishes the outer retina (photoreceptors) and absorbs stray light.', { aka: ['choroid of eye'], micro: 'capillary' }),
  'ciliary body': S('Ring of tissue behind the iris containing the ciliary muscle and ciliary processes.', 'Between choroid and iris.', 'Ciliary processes secrete aqueous humour; the ciliary muscle changes lens shape for focusing (accommodation).', { aka: ['ciliary muscle', 'ciliary processes', 'corona ciliaris'], innervation: 'Parasympathetic from CN III via the ciliary ganglion.', clinical: 'Age-related loss of accommodation (presbyopia) makes reading glasses necessary after ~45 years.' }),
  'iris': S('Coloured contractile diaphragm in front of the lens with a central aperture, the pupil.', 'Between cornea and lens, dividing anterior and posterior chambers.', 'Controls the amount of light entering the eye (sphincter pupillae — parasympathetic; dilator pupillae — sympathetic).', { aka: ['pupil'], clinical: 'A fixed dilated pupil suggests CN III compression; pinpoint pupils suggest opioids or a pontine lesion.' }),
  'lens': S('Transparent biconvex structure held by zonular fibres behind the iris.', 'Behind the iris and pupil.', 'Fine-focuses light onto the retina; changes shape in accommodation.', { aka: ['lens of eye', 'crystalline lens'], clinical: 'Cataract (lens opacity) is the leading cause of reversible blindness worldwide; treated by replacing the lens.' }),
  'zonular fibres': S('Suspensory ligament of the lens: fine fibres from the ciliary body to the lens capsule.', 'Around the lens equator.', 'Hold the lens; relax when the ciliary muscle contracts, letting the lens round up for near vision.', { aka: ['suspensory ligament of lens', 'zonule', 'ciliary zonule'] }),
  'aqueous humour': S('Clear watery fluid filling the anterior and posterior chambers.', 'Between cornea and lens.', 'Nourishes the lens and cornea and maintains intraocular pressure; drains through the trabecular meshwork into the scleral venous sinus (canal of Schlemm).', { aka: ['aqueous humor', 'aqueous humor of eyeball', 'anterior chamber of eyeball', 'anterior chamber', 'posterior chamber', 'eye trabecular meshwork', 'trabecular meshwork', 'scleral venous sinus', 'canal of schlemm'], clinical: 'Impaired drainage raises pressure and damages the optic nerve (glaucoma).' }),
  'vitreous body': S('Transparent gel filling the posterior four-fifths of the eyeball.', 'Between lens and retina.', 'Maintains the shape of the eye and holds the retina against the choroid.', { aka: ['vitreous humor', 'humor of vitreous body', 'vitreous humour'], clinical: 'Floaters are condensations in the vitreous; sudden showers may signal retinal detachment.' }),
  'retina': S('Light-sensitive neural layer lining the back of the eye, containing ~120 million rods and ~6 million cones.', 'Inner coat of the posterior eyeball, ending at the ora serrata.', 'Converts light to electrical signals and begins visual processing; ganglion cell axons form the optic nerve.', { aka: ['optic part of retina', 'ora serrata'], micro: 'neuron', blood: 'Central retinal artery (inner layers) and choroid (outer layers).', clinical: 'Retinal detachment, diabetic retinopathy and age-related macular degeneration are major causes of vision loss.' }),
  'macula lutea': S('Yellowish spot of the retina lateral to the optic disc.', 'Posterior pole of the eye.', 'Central, high-acuity and colour vision.', { aka: ['macula', 'fovea centralis', 'fovea'], clinical: 'The fovea at its centre contains only cones — it is where you look; macular degeneration destroys central vision.' }),
  'optic disc': S('Pale circular area where the optic nerve leaves the eye and the retinal vessels enter.', 'About 3 mm medial to the fovea.', 'Contains no photoreceptors — the physiological blind spot.', { aka: ['optic nerve head', 'blind spot'], clinical: 'Swelling of the disc (papilloedema) signals raised intracranial pressure.' }),
  'conjunctiva': S('Thin transparent mucous membrane lining the eyelids (palpebral) and covering the sclera (bulbar).', 'Eyelids and front of the eyeball.', 'Protects and lubricates the eye; forms the conjunctival sac.', { aka: ['bulbar conjunctiva', 'palpebral conjunctiva of upper eyelid', 'palpebral conjunctiva of lower eyelid', 'palpebral conjunctiva'], clinical: 'Conjunctivitis ("pink eye"); pallor of the palpebral conjunctiva suggests anaemia.' }),
  'tarsal plate': S('Plate of dense connective tissue forming the skeleton of each eyelid, containing tarsal (meibomian) glands.', 'Upper and lower eyelids.', 'Gives the eyelids shape and stiffness; meibomian oil stops tears evaporating.', { aka: ['superior tarsus', 'inferior tarsus', 'tarsal plate of upper eyelid', 'tarsal plate of lower eyelid'], clinical: 'Blocked meibomian glands form a chalazion.' }),
  'lacrimal gland': S('Almond-shaped gland in the upper lateral orbit.', 'Lacrimal fossa of the frontal bone.', 'Secretes tears that moisten, clean and protect the cornea.', { innervation: 'Parasympathetic from the facial nerve via the greater petrosal nerve and pterygopalatine ganglion.', clinical: 'Dry eye results from reduced secretion (e.g. Sjögren syndrome).' }),
  'lacrimal drainage system': S('Pathway draining tears from the eye to the nose.', 'Medial canthus to the inferior meatus of the nose.', 'Tears enter the puncta → lacrimal canaliculi → lacrimal sac → nasolacrimal duct → inferior meatus.', { aka: ['lacrimal canaliculus', 'ampulla of lacrimal canaliculus', 'lacrimal sac', 'nasolacrimal duct', 'lacrimal lake', 'lacrimal punctum'], clinical: 'Blocked nasolacrimal duct causes watery eyes in infants; infection of the sac is dacryocystitis. Crying makes your nose run for this reason.' }),

  // =============================== ear ===============================
  'external ear': S('The auricle (pinna) of elastic cartilage and the external acoustic meatus.', 'Side of the head.', 'Collects and directs sound waves to the tympanic membrane; helps localise sound.', { aka: ['auricle', 'pinna', 'external acoustic meatus'], clinical: 'A haematoma of the auricle must be drained to prevent "cauliflower ear".' }),
  'auditory tube': S('Pharyngotympanic (Eustachian) tube linking the middle ear with the nasopharynx.', 'From the middle ear forward and down to the nasopharynx (~36 mm).', 'Equalises pressure on both sides of the tympanic membrane and drains the middle ear.', { aka: ['pharyngotympanic tube', 'eustachian tube'], clinical: 'Shorter and more horizontal in children, explaining the frequency of middle-ear infection (otitis media).' }),

  // =============================== skin & appendages ===============================
  'skin': S('The body\'s largest organ (~1.8 m², ~4 kg): epidermis, dermis and hypodermis.', 'Covers the whole body; thickness ~0.5 mm (eyelids) to ~4 mm (back).', 'Barrier against water loss, microbes and UV; thermoregulation (sweat, blood flow); sensation; vitamin D synthesis.', { aka: ['skin of body', 'integument'], structure: 'Epidermis (keratinised stratified squamous epithelium: basal, spinous, granular, (lucid), cornified layers) with melanocytes and Langerhans cells; dermis (papillary and reticular) with vessels, nerves, glands and hair follicles; hypodermis of fat.', clinical: 'Burns are classified by depth; melanoma, basal and squamous cell carcinoma are the main skin cancers.', micro: 'cell' }),
  'hair': S('Keratinised filaments growing from follicles in the dermis; each has an arrector pili muscle and sebaceous gland.', 'Almost all skin except palms, soles, lips and parts of genitalia.', 'Protection, insulation, sensation and social signalling.', { aka: ['hair of head', 'pubic hair', 'eyebrow', 'eyebrows', 'scalp hair'], clinical: 'Hair grows ~1 cm a month; male-pattern baldness is androgen-driven.' }),
  'lip': S('Muscular folds (orbicularis oris) covered by skin outside and mucosa inside, with the red vermilion between.', 'Around the oral fissure.', 'Closure of the mouth, speech, facial expression and sensation.', { aka: ['lips'], clinical: 'The vermilion is pink because its thin epithelium shows the underlying capillaries; cyanosis shows first here.' }),
};
