// Short overviews of each system and region (shown before anything is selected).
export const SYSTEM_OVERVIEWS: Record<string, string> = {
  integumentary: 'The skin is the body\'s largest organ (≈1.8 m², ≈16% of body weight): a stratified epidermis over a vascular dermis and a fatty hypodermis. It protects, regulates temperature, senses touch, pain and temperature, and synthesises vitamin D. Hair, nails and glands are its appendages.',
  skeletal: 'The adult skeleton has 206 bones: 80 axial (skull, vertebral column, ribs, sternum, hyoid) and 126 appendicular (limbs and girdles). Bone supports and protects, anchors muscles, stores calcium and phosphate, and houses red marrow for blood formation. Bones meet at fibrous, cartilaginous and synovial joints.',
  muscular: 'About 600 skeletal muscles make up ~40% of body mass. Each attaches by tendons or aponeuroses from an origin (usually proximal, fixed) to an insertion (distal, mobile). Muscles act in groups — prime movers, antagonists, synergists and fixators — and are supplied by somatic motor nerves.',
  cardiovascular: 'A four-chambered heart pumps ~5 L of blood per minute at rest through two circuits: the pulmonary circulation (right heart → lungs) and the systemic circulation (left heart → body). Arteries carry blood away from the heart, capillaries exchange gases and nutrients, and veins return blood to the heart.',
  nervous: 'The central nervous system (brain and spinal cord) integrates information; the peripheral nervous system (12 pairs of cranial and 31 pairs of spinal nerves with their plexuses and ganglia) connects it to the body. Autonomic (sympathetic and parasympathetic) divisions control viscera, vessels and glands.',
  sensory: 'Special senses: the eye (fibrous, vascular and neural tunics with the refractive cornea and lens) and the ear. Extraocular muscles, eyelids and the lacrimal apparatus protect and move the eye.',
  respiratory: 'The conducting airway (nose, pharynx, larynx, trachea, bronchi) warms, humidifies and filters air, delivering it to ~480 million alveoli with ~70 m² of gas-exchange surface. The right lung has three lobes and ten bronchopulmonary segments; the left has two lobes.',
  digestive: 'The alimentary canal (mouth → pharynx → oesophagus → stomach → small and large intestine → anal canal) is about 9 m long. Accessory organs — salivary glands, liver, gallbladder and pancreas — add secretions for digestion and absorption.',
  urinary: 'The kidneys filter ~180 L of plasma per day through ~1 million nephrons each, producing 1–2 L of urine that passes through the ureters to the bladder and out through the urethra. They also regulate blood pressure, acid–base balance and red cell production.',
  reproductive: 'The gonads (testes or ovaries) produce gametes and sex hormones; ducts, glands and external genitalia transport gametes and, in the female, support fertilisation and pregnancy.',
  endocrine: 'Ductless glands — pituitary, pineal, thyroid, parathyroids, adrenals, pancreatic islets and gonads — release hormones into the blood that regulate growth, metabolism, reproduction and stress responses.',
  lymphatic: 'Lymphatic vessels return ~3 L/day of tissue fluid to the veins and carry absorbed fat. Lymph nodes filter lymph along the way; the spleen, thymus, tonsils and mucosa-associated lymphoid tissue house the immune cells.',
};

export const REGION_OVERVIEWS: Record<string, string> = {
  head: 'The head contains the brain within the cranium, the special sense organs, and the entrances to the respiratory and digestive tracts. Superficially the muscles of facial expression lie in the subcutaneous tissue; deeper lie the muscles of mastication.',
  neck: 'The neck joins head and trunk. The sternocleidomastoid divides each side into anterior and posterior triangles. It carries the airway, oesophagus, carotid arteries, jugular veins, vagus nerves, thyroid gland and the cervical vertebrae with their muscles.',
  thorax: 'The thoracic cage of ribs, sternum and thoracic vertebrae protects the heart, lungs and great vessels. The mediastinum between the lungs holds the heart, trachea, oesophagus and thymus. Breathing muscles — diaphragm and intercostals — change its volume.',
  abdomen: 'The abdominal wall (external and internal oblique, transversus abdominis, rectus abdominis) encloses the peritoneal cavity with the stomach, intestines, liver, gallbladder, pancreas and spleen, and the retroperitoneal kidneys, adrenal glands, aorta and inferior vena cava.',
  pelvis: 'The bony pelvis (hip bones, sacrum, coccyx) transmits body weight to the legs and contains the bladder, rectum and internal reproductive organs, supported by the pelvic floor (levator ani and coccygeus). The perineum lies below it.',
  back: 'The back contains the vertebral column and spinal cord, superficial muscles that move the upper limb (trapezius, latissimus dorsi, rhomboids, levator scapulae) and the deep (intrinsic) back muscles — erector spinae and transversospinalis — that extend and stabilise the spine.',
  shoulder: 'The shoulder girdle (clavicle and scapula) connects the arm to the trunk. The glenohumeral joint is the most mobile joint of the body, stabilised mainly by the rotator cuff — supraspinatus, infraspinatus, teres minor and subscapularis — and covered by the deltoid.',
  arm: 'The arm (brachium) lies between shoulder and elbow around the humerus. Its anterior compartment (biceps brachii, brachialis, coracobrachialis) flexes and is supplied by the musculocutaneous nerve; the posterior compartment (triceps) extends and is supplied by the radial nerve.',
  forearm: 'The forearm contains the radius and ulna, which rotate around each other in pronation and supination. Anterior flexor-pronator muscles (median and ulnar nerves) and posterior extensor-supinator muscles (radial nerve) control the wrist and fingers.',
  hand: 'The hand has 27 bones (8 carpals, 5 metacarpals, 14 phalanges). Long tendons from the forearm and small intrinsic muscles (thenar, hypothenar, lumbricals, interossei) give it both power and precision grip.',
  thigh: 'The femur is surrounded by three compartments: anterior (quadriceps, sartorius — femoral nerve), medial (adductors, gracilis — obturator nerve) and posterior (hamstrings — sciatic nerve).',
  knee: 'The knee is a modified hinge joint between femur, tibia and patella, stabilised by the cruciate and collateral ligaments, with the medial and lateral menisci cushioning the tibial plateau.',
  leg: 'The leg holds the tibia and fibula in three compartments: anterior (dorsiflexors — deep fibular nerve), lateral (fibularis longus and brevis — superficial fibular nerve) and posterior (gastrocnemius, soleus and deep flexors — tibial nerve).',
  foot: 'The foot has 26 bones (7 tarsals, 5 metatarsals, 14 phalanges) arranged in longitudinal and transverse arches, supported by ligaments, the plantar aponeurosis and four layers of intrinsic plantar muscles.',
};
